apps/api/package.json
apps/api/src/auth/auth.controller.spec.ts
apps/api/src/auth/auth.controller.ts
apps/api/src/auth/auth.module.ts
apps/api/src/auth/auth.service.ts
apps/api/src/auth/jwt.strategy.ts
apps/api/src/core/app.controller.spec.ts
apps/api/test/app.e2e-spec.ts
apps/api/test/jest-unit.json

O AuthController foi criado sem testes.
- Adiciona Testes para o AuthController
- Configura o JWTService pra carregar a secret do arquivo .env. `JWT_KEY`
https://github.com/mattd-silva22/IC045-marketplace-ufba/pull/14

AuthController test

---

apps/api/.env.example

Precisamos de um arquivo .env de exemplo

Add .env.example

---

apps/web/app/encontrar-demandas/page.tsx
apps/web/app/globals.css
apps/web/components/DemandList/Item.tsx
apps/web/components/DemandList/index.tsx
apps/web/components/DemandList/types.ts
apps/web/components/ui/button.tsx
apps/web/components/ui/checkbox.tsx
apps/web/components/ui/input.tsx
apps/web/components/ui/label.tsx
apps/web/components/ui/select.tsx
apps/web/package-lock.json
apps/web/package.json
apps/web/tailwind.config.ts

Criada base do front-end da página encontrar demandas com dados mockados.

feat:Página '/encontrar-demandas' criada com mockup (#33)

---

apps/web/components/ui/drawer.tsx
apps/web/hooks/useMediaQuery.tsx
apps/web/modules/components/header/header.tsx
apps/web/package.json
apps/web/yarn.lock

Adiciona estilo do header responsivo

feat: Mobile Header criado

---

.github/workflows/deploy.yaml

> _Adicione uma breve descrição para o problema a ser solucionado Ou a feature a qual está atuando._   
> Exemplos: 
> Exemplos:

Update workflow name

---

apps/api/src/core/app.module.ts
apps/api/src/demand/demand.controller.ts
apps/api/src/demand/demand.dto.ts
apps/api/src/demand/demand.module.ts
apps/api/src/demand/demand.service.ts
apps/api/src/demand/tests/demand.controller.spec.ts
apps/api/src/demand/tests/demand.e2e-spec.ts
apps/api/src/demand/tests/demand.service.spec.ts
apps/api/src/research-group/tests/fixtures.ts
apps/api/src/types.ts
apps/api/src/user/user.service.ts

Precisamos de CRUD para demandas

CRUD Demanda

---

apps/api/package.json
apps/api/src/main.ts

> O sistema não tem uma interface que descreva as rotas já criadas.
> - [x] Adiciona uma interface de documentação da API

feat: add swegger

---

apps/web/app/cadastro-demandas/page.tsx

Este PR adiciona o arquivo "cadastro-demandas/page.tsx", que inclui a implementação do frontend para o cadastro de demandas. Entretanto, o componente de cadastrar demandas se encontra sem o backend funcionando no momento, mas possui um código comentado para futura implementação.
- Adicionado o diretório `cadastro-demandas`.
- Criado o arquivo `page.tsx`.

Adicionando a página de cadastro de demandas sem o backend 

---

apps/api/package-lock.json
apps/api/src/project/project.dto.ts
apps/api/src/project/project.service.ts
apps/web/package.json
docker-compose.yml

> _Adicione uma breve descrição para o problema a ser solucionado Ou a feature a qual está atuando._   
> Exemplos: 
> Exemplos:

Fix docker entrypoint

---

.github/workflows/ci.yaml
apps/api/src/admin/admin.controller.spec.ts
apps/api/src/admin/admin.controller.ts
apps/api/src/admin/admin.module.ts
apps/api/src/admin/admin.service.spec.ts
apps/api/src/admin/admin.service.ts
apps/api/src/core/app.module.ts
apps/api/src/main.ts
apps/api/src/project/project.controller.ts
apps/api/src/project/project.service.ts
apps/api/src/roles/roles.decorator.ts
apps/api/src/roles/roles.guard.ts
apps/api/src/user/user.dto.ts

A branch `dev` não roda os testes durante o PR
> Exemplos: 
> Exemplos:

Add check on dev branch

---

apps/api/src/tags/tags.controller.ts
apps/api/src/tags/tags.service.ts
package-lock.json

> _O modulo keywords estava com a referencias a tabela do banco desatualizada_   
> _Endpoint do modulo Keywords estava com a nomenclatura desatualizada_ 
> - [x] Altera as referencia a tabela 'tags' para 'keywords'.
> - [x] Alterei o endpoint de /tags para /keywords, conforme padrão do projeto.

Fix/backend - Modulo Keywords

---

apps/api/src/demand/demand.dto.ts
apps/web/app/cadastro-demandas/page.tsx
apps/web/app/layout.tsx

> _Após adicionar a funcionalidade do backend a "page.tsx" de cadastro-demandas, a página quebrava no navegador por causa do QueryClient._   
> _Este PR altera o arquivo de layout global para adicionar a funcionalidade do ReactQueryProvider e realiza a integração entre o frontend e o backend._  
> Exemplos:
> - [X] Adição da integração do front com o back no arquivo "/apps/web/app/cadastro-demandas/page.tsx"
> - [X] Adiciona a funcionalidade do ReactQueryProvider ao arquivo "/apps/web/layout.tsx" para resolver o erro de "Error: No QueryClient set, use QueryClientProvider to set one"
> - [X] Adiciona o campo "links?" ao arquivo "/apps/api/src/demand/demand.dto.ts" para evitar erros ao cadastrar demandas
> - [X] Instalação do pacote "tanstack/react-query" para o React-Query e adição do …

Resolução do problema de 'QueryClient' set na página de cadastro-demandas e integração do front com back

---

apps/web/app/cadastro-demandas/page.tsx
apps/web/package-lock.json

> _Adicione uma breve descrição para o problema a ser solucionado Ou a feature a qual está atuando._   
> Exemplos: 
> Exemplos:

Fix provider

---

apps/web/app/cadastro-projetos/page.tsx
apps/web/modules/cadastro-projetos/CadastroProjetosPage.tsx

> _Implementa visualmente a tela de cadastro de projetos no caminho /cadastro-projetos_

Adicionar página de cadastrar projetos (Somente front-end)

---

apps/api/src/auth/auth.service.ts
apps/web/api/user.service.ts
apps/web/app/login/page.tsx
apps/web/app/recuperar-senha/page.tsx

> A tela de recuperar senha já foi totalmente implementada.
[x] adiciona o link de recuperar senha na tela de login

Add recuperar-senha link into login page

---

apps/web/modules/components/header/header.tsx

> _Adicione uma breve descrição para o problema a ser solucionado Ou a feature a qual está atuando._   
> Exemplos: 
> Exemplos:

fix home page

---

docker-compose.yml

Necessidade de subir o frontend quando sobe o sistema.

Adição do frontend no docker compose para subir o ambiente

---

apps/web/context/UserContext.tsx

> Mensagem de erro: localStorage undefined sendo apresentado em todas as telas
> Chama o localStorage dentro de um useEffect ao invés de chamá-lo diretamente

fix: Corrigir erro do localstorage undefined

---

apps/web/modules/components/header/header.tsx

> _Link Meus Grupos de pesquisa do header levava à página principal_   
> _Link Meus Grupos de pesquisa do header leva à página Meus Grupos de pesquisa_

fix link to page Meus Grupos de pesquisa

---

apps/api/prisma/seed/researchgroups.ts
apps/api/prisma/seed/users.ts
apps/api/src/auth/tests/auth.controller.e2e-spec.ts
apps/web/app/cadastro-demandas/page.tsx

- No cadastro de demanda, botão de cancelar aparecia na frente do botão de cadastrar.
- classe css estava com reverse. Ajuste feito para ficar na ordem correta.

Fix button demand

---

.github/workflows/ci.yaml
apps/api/src/main.ts
apps/web/app/alterar-senha/page.tsx
apps/web/app/login/page.tsx
apps/web/app/recuperar-senha/page.tsx
apps/web/app/user-register/page.tsx
apps/web/components/MyResearchGroupList/Item.tsx
apps/web/components/ResearchGroupList/Item.tsx
apps/web/components/ui/button.tsx
apps/web/components/ui/input.tsx
apps/web/components/ui/multi-select.tsx
apps/web/context/loginContext/index.ts
apps/web/lib/access.control.ts
apps/web/modules/detalhe-grupo-pesquisa/detalheGrupoPesquisaPage.tsx
apps/web/modules/login/loginPage.tsx
apps/web/modules/minhas-demandas/components/filter/minhasDemandasFilter.tsx
apps/web/next.config.mjs
apps/web/package-lock.json
apps/web/package.json

Corrige os problemas do frontend e adiciona check no github actions

add frontend build to github

---

apps/web/app/user-register/page.tsx

Corrige o erro de "Tipo de cadastro inválido" ao tentar cadastrar um usuário

feat: Adiciona valores padrão ao formulário de registro de usuário

---

apps/web/app/encontrar-demandas/page.tsx
apps/web/components/ui/button.tsx

> Página encontrar demandas não está tomando o tamanho total do container
> Estilos do botão desatualizados
> Filtros a serem retirados da página de encontrar demandas
> Estilo do botão corrigido
> Página encontrar demandas corrigida

Fix encontrar demandas

---

apps/web/app/encontrar-demandas/page.tsx
apps/web/components/ui/button.tsx
apps/web/modules/cadastro-projetos/CadastroProjetosPage.tsx
apps/web/modules/components/header/header.tsx
apps/web/modules/detalhe-grupo-pesquisa/detalheGrupoPesquisaPage.tsx

> Problemas na tela de cadastrar projetos
> Permite cadastro sem data fim
> Bloqueia cadastro com data fim anterior a data inicio

Fix Cadastro de Projetos

---

apps/api/package.json
apps/web/package.json
prod/docker-compose.yml

> _Não era possível subir o sistema no modo de produção._   
> - [x] Altera os scripts de inicialização do next e nest para produção
> - [X] Adiciona um docker-compose para produção

alteração do docker-compose.yml e dos package.json 

---

apps/api/prisma/seed/companies.ts
apps/api/prisma/seed/demands.ts
apps/api/prisma/seed/projects.ts

Os dados da carga inicial são pobres. Isso pode nos enganar nos testes de interface. Necessário aumentar a qualidade dos dados presentes na seed
Atualiza os arquivos das seeds, inserindo dados mais próximos do real.

Melhoria na qualidade dos dados presentes no seed

---

apps/web/modules/minhas-demandas/components/table/minhasDemandasTable.tsx

Solicitação de mudança de nome em campo da tabela. Issue #181 
Ajusta título da tabela de `Criado em` para `Data de Criação`.

Alteração no título da tabela de minhas demandas

---

README.md

É necessário ter um passo-a-passo de como executar o sistema.
Adiciona link para instrução de execução.

Adição de instrução de execução

---

apps/web/modules/components/header/header.tsx

Atender solicitação da issue #173 . Mostrar item de menu dentro do Popover 
Adiciona  no Popover o item Meus Grupos de Pesquisa quando for Pesquisador e Minhas demandas quando for Empresa.
Ainda deixei os mesmo itens no menu para que o professor escolha o que melhor agrade.

Adição de itens no menu Popover

---

apps/api/src/demand/demand.service.ts
apps/api/src/demand/tests/demand.service.spec.ts
apps/web/api/demandas/use-edit-demand.ts
apps/web/api/demandas/use-get-one-private-demand.ts
apps/web/app/minhas-demandas/[id]/page.tsx
apps/web/app/minhas-demandas/page.tsx
apps/web/modules/minhas-demandas/components/table/minhasDemandasTable.tsx
apps/web/modules/minhas-demandas/interfaces/demanda.ts

> Cria a tela de editar demanda
**Obs: Não consegui implementar a edição da parte "Demanda Pública" pois o componente do switch não estava funcionando corretamente**

feat: implements demand editing

---

apps/api/src/research-group/research-group.controller.ts
apps/api/src/research-group/research-group.module.ts
apps/api/src/research-group/research-group.service.ts
apps/api/src/research-group/tests/research-group.controller.spec.ts
apps/web/api/research-group/use-add-research-group.ts
apps/web/app/cadastro-grupos-pesquisa/page.tsx
apps/web/app/meus-grupos-pesquisa/page.tsx
apps/web/modules/cadastro-grupos-pesquisa/CadastroGruposPesquisaPage.tsx
apps/web/types/researchGroup.ts

A aplicação ainda não tinha cadastro de grupo de pesquisa  
Implementa de forma simples o cadastro de Grupo de Pesquisa.
Adiciona rota para que página Meus Grupos de Pesquisa redirecione para Novo Grupo de Pesquisa.

Cadastro de Grupo de Pesquisa

---

.github/workflows/deploy.yaml

> _O comando para subir o banco de dados estava errado._

Correção do arquivo "deploy.yml"

---

apps/web/app/cadastro-demandas/page.tsx
apps/web/app/encontrar-grupo-pesquisa/contactar-grupo-pesquisa/page.tsx
apps/web/app/minhas-demandas/[id]/page.tsx
apps/web/app/minhas-demandas/page.tsx
apps/web/components/MyResearchGroupList/Item.tsx
apps/web/components/ui/select.tsx
apps/web/modules/cadastro-grupos-pesquisa/CadastroGruposPesquisaPage.tsx
apps/web/modules/cadastro-projetos/CadastroProjetosPage.tsx
apps/web/modules/components/footer/footer.tsx
apps/web/modules/contactar-empresa/index.tsx
apps/web/modules/contactar-grupo-pesquisa/components/index.tsx
apps/web/modules/detalhe-grupo-pesquisa/detalheGrupoPesquisaPage.tsx
apps/web/modules/meus-grupos-pesquisa/components/filter/meusGruposPesquisaFilter.tsx
apps/web/modules/minhas-demandas/components/filter/minhasDemandasFilter.tsx
apps/web/modules/minhas-demandas/components/modal/deleteModal.tsx
apps/web/modules/minhas-demandas/components/table/minhasDemandasTable.tsx
apps/web/modules/painel-administrativo/components/UsersTable/columns.tsx

Issues:
120 176 180 182 218 219 220 221 224

Issues 120 176 180 182 218 219 220 221 224

---

apps/api/src/demand/demand.service.ts
apps/web/lib/utils.ts
apps/web/lib/utils.tsx
apps/web/modules/minhas-demandas/components/table/minhasDemandasTable.tsx
apps/web/tailwind.config.ts

Precisamos adicionar status a demanda

Adiciona status a demanda

---

apps/api/package-lock.json
apps/api/src/research-group/research-group.service.ts
apps/web/api/research-group/use-edit-research-group.ts
apps/web/api/research-group/use-get-one-research-group.ts
apps/web/app/editar-grupo-pesquisa/[id]/page.tsx
apps/web/components/MyResearchGroupList/Item.tsx
apps/web/components/MyResearchGroupList/type.ts
apps/web/modules/meus-grupos-pesquisa/interfaces/grupo-pesquisa.ts

Este PR adiciona apenas a edição de grupo de pesquisa

Adição de novas interfaces e hooks para edição de grupos de pesquisa
